### ISSUE TITLE
Issue with Rekal plugins on Windows 10 x64

### ISSUE THREAD

**Issue by chintanhshah** [google/rekall-profiles#17]
Just wanted to post the issue while running the rekall plugins with manual profile path on 64 bit Windows 10 systems . Appreciate any inputs on what might be going wrong . 

While executing basic process listing plugins on 64 bit Windows 10 VMs , it throws an exceptions. This is observed with all the plugins . Here is what is being essentially done : 

Profiles have been verified using version_scan and it is correct . Any idea about the below exception ?

**#scl enable python27 "/var/attivo/rekall/bin/rekal.py --profile ntkrnlmp.json -f memory.2d1e1316_win1064bit.img pslist"**

  _EPROCESS            Name          PID   PPID   Thds    Hnds    Sess  Wow64           Start                     Exit
-------------- -------------------- ----- ------ ------ -------- ------ ------ ------------------------ ------------------------
2016-12-09 06:59:32,770:WARNING:rekall.1:Buffer has no offset in object _UNICODE_STRING. Check that vtypes has a concrete definition for it.
2016-12-09 06:59:32,784:CRITICAL:rekall.1:Traceback (most recent call last):
  File "/var/attivo/rekall/lib/python2.7/site-packages/rekall/session.py", line 840, in RunPlugin
    result = plugin_obj.render(ui_renderer) or plugin_obj
  File "/var/attivo/rekall/lib/python2.7/site-packages/rekall/plugin.py", line 678, in render
    for row in self.collect():
  File "/var/attivo/rekall/lib/python2.7/site-packages/rekall/plugins/windows/taskmods.py", line 69, in collect
    for task in self.filter_processes():
  File "/var/attivo/rekall/lib/python2.7/site-packages/rekall/plugins/windows/common.py", line 447, in filter_processes
    for proc in self.list_eprocess():
  File "/var/attivo/rekall/lib/python2.7/site-packages/rekall/plugins/windows/common.py", line 495, in list_eprocess
    for proc in self.session.GetParameter("pslist_%s" % method):
  File "/var/attivo/rekall/lib/python2.7/site-packages/rekall/session.py", line 742, in GetParameter
    result = self._RunParameterHook(item)
  File "/var/attivo/rekall/lib/python2.7/site-packages/rekall/session.py", line 777, in _RunParameterHook
    result = hook.calculate()
  File "/var/attivo/rekall/lib/python2.7/site-packages/rekall/plugins/windows/common.py", line 646, in calculate
    if handle.get_object_type() == "Process":
  File "/var/attivo/rekall/lib/python2.7/site-packages/rekall/plugins/overlays/windows/win7.py", line 177, in get_object_type
    self.TypeIndex].Name.v()
  File "/var/attivo/rekall/lib/python2.7/site-packages/rekall/plugins/overlays/windows/common.py", line 651, in v
    data = self.Buffer.dereference_as(
  File "/var/attivo/rekall/lib/python2.7/site-packages/rekall/obj.py", line 1425, in __getattr__
    raise AttributeError(attr)
AttributeError: Buffer

2016-12-09 06:59:32,785:CRITICAL:root:Buffer. Try --debug for more information.
Traceback (most recent call last):
  File "/var/attivo/rekall/bin/rekal.py", line 113, in <module>
    main()
  File "/var/attivo/rekall/bin/rekal.py", line 110, in main
    user_session.Flush()
  File "/var/attivo/rekall/lib/python2.7/site-packages/rekall/session.py", line 1100, in Flush
    hook(*args)
  File "/var/attivo/rekall/lib/python2.7/site-packages/rekall/cache.py", line 251, in Flush
    self.SetFingerprint(self.session.GetParameter("image_fingerprint"))
  File "/var/attivo/rekall/lib/python2.7/site-packages/rekall/session.py", line 742, in GetParameter
    result = self._RunParameterHook(item)
  File "/var/attivo/rekall/lib/python2.7/site-packages/rekall/session.py", line 777, in _RunParameterHook
    result = hook.calculate()
  File "/var/attivo/rekall/lib/python2.7/site-packages/rekall/plugins/windows/misc.py", line 285, in calculate
    for task in self.session.plugins.pslist().filter_processes():
  File "/var/attivo/rekall/lib/python2.7/site-packages/rekall/plugins/windows/common.py", line 447, in filter_processes
    for proc in self.list_eprocess():
  File "/var/attivo/rekall/lib/python2.7/site-packages/rekall/plugins/windows/common.py", line 495, in list_eprocess
    for proc in self.session.GetParameter("pslist_%s" % method):
  File "/var/attivo/rekall/lib/python2.7/site-packages/rekall/session.py", line 742, in GetParameter
    result = self._RunParameterHook(item)
  File "/var/attivo/rekall/lib/python2.7/site-packages/rekall/session.py", line 777, in _RunParameterHook
    result = hook.calculate()
  File "/var/attivo/rekall/lib/python2.7/site-packages/rekall/plugins/windows/common.py", line 646, in calculate
    if handle.get_object_type() == "Process":
  File "/var/attivo/rekall/lib/python2.7/site-packages/rekall/plugins/overlays/windows/win7.py", line 177, in get_object_type
    self.TypeIndex].Name.v()
  File "/var/attivo/rekall/lib/python2.7/site-packages/rekall/plugins/overlays/windows/common.py", line 651, in v
    data = self.Buffer.dereference_as(
  File "/var/attivo/rekall/lib/python2.7/site-packages/rekall/obj.py", line 1425, in __getattr__
    raise AttributeError(attr)
AttributeError: Buffer

**Comment by scudette** [comment]
This normally occurs because the profile is missing a struct that should be
there, such as Unicode_string. This happens when Microsoft releases corrupt
pdb files. Can you please indicate the guid of the profile, so I can
forward to Microsoft?

**Comment by chintanhshah** [comment]
Hi , 

Here is the GUID of the profile : 

4DAC3B582A9147ECAED2644CB165222B2 ntkrnlmp.pdb

**Comment by chintanhshah** [comment]
Hi ,

Just reconnecting and check if this issue is fixed ? Should I try with the latest released 1.6.0 rekall version ?

**Comment by scudette** [comment]
I think this should work now? I see the _UNICODE_STRING is defined in this files now (Uploaded Sept 2017).
