### ISSUE TITLE
Exception on any plugin with Win10-profile 0CBB2B1DC6DE4284BB54F28DEE3E0FA81

### ISSUE THREAD

**Issue by DeKe42** [google/rekall-profiles#33]
This might be related to #17 ?

On my development machine, a new profile had to be built this morning (0CBB2B1DC6DE4284BB54F28DEE3E0FA81). Using this profile, any plugin fails with a stacktrace like this:

```
[1] Live (Memory) 09:42:15> pslist
--------------------------> pslist()
2017-10-16 09:42:15,612:DEBUG:rekall.1:Running plugin (pslist) with args (()) kwargs ({})
2017-10-16 09:42:15,612:CRITICAL:rekall.1:Traceback (most recent call last):
  File "d:\cmc\rekall\rekall-core\rekall\session.py", line 858, in RunPlugin
    plugin_obj = self._GetPluginObj(plugin_obj, *args, **kwargs)
  File "d:\cmc\rekall\rekall-core\rekall\session.py", line 917, in _GetPluginObj
    return plugin_cls(*args, **kwargs)
  File "d:\cmc\rekall\rekall-core\rekall\obj.py", line 139, in __call__
    return self._target(*(self._args + args), **new_kwargs)
  File "d:\cmc\rekall\rekall-lib\rekall_lib\registry.py", line 72, in __call__
    res = super(UniqueObjectIdMetaclass, cls).__call__(*args, **kwargs)
  File "d:\cmc\rekall\rekall-core\rekall\plugin.py", line 861, in __init__
    self.session.plugins.load_as().GetVirtualAddressSpace()
  File "d:\cmc\rekall\rekall-core\rekall\plugins\core.py", line 414, in GetVirtualAddressSpace
    self.session.kernel_address_space = find_dtb.CreateAS(dtb)
  File "d:\cmc\rekall\rekall-core\rekall\plugins\core.py", line 264, in CreateAS
    profile=self.profile)
  File "d:\cmc\rekall\rekall-lib\rekall_lib\registry.py", line 72, in __call__
    res = super(UniqueObjectIdMetaclass, cls).__call__(*args, **kwargs)
  File "d:\cmc\rekall\rekall-core\rekall\plugins\windows\pagefile.py", line 368, in __init__
    self.prototype_mask = pte.u.Proto.Prototype.mask
  File "d:\cmc\rekall\rekall-core\rekall\obj.py", line 1433, in __getattr__
    raise AttributeError(attr)
AttributeError: u
```

**Comment by scudette** [comment]
Yes this is the same issue. If you look carefully at the JSON file generated from the pdb file it does not have a $STRUCTS section at all. I think MS will eventually fix the problem on their end since the issue you mention #17 shows a corrected GUID was uploaded to the repository around sept 2017 which works (In that issue the _UNICODE_STRING symbol was missing).

We should add some minimal sanity checking for generated profiles to let people know about the broken symbols and reject the profile (Rekall maintains a list of rejected GUIDs which failed for some reason). We periodically retry these rejected ones so maybe we can update in future when MS fixes their end.
